name: Bug Report
description: Report a bug or issue with the MongoDB Grafana plugin
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Configure '...'
        3. Run query '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: grafana-version
    attributes:
      label: Grafana Version
      description: What version of Grafana are you using?
      placeholder: e.g., 10.2.0
    validations:
      required: true

  - type: input
    id: mongodb-version
    attributes:
      label: MongoDB Version
      description: What version of MongoDB are you using?
      placeholder: e.g., 6.0.3
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the mongodb-grafana plugin are you using?
      placeholder: e.g., 0.8.1
    validations:
      required: true

  - type: input
    id: nodejs-version
    attributes:
      label: Node.js Version
      description: What version of Node.js is the proxy server running on?
      placeholder: e.g., 16.20.0
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: query
    attributes:
      label: MongoDB Query
      description: If applicable, paste the MongoDB aggregation query you're using
      placeholder: |
        db.collection.aggregate([
          // Your query here
        ])
      render: javascript

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant log output from:
        - Grafana server logs
        - MongoDB proxy logs
        - Browser console (if applicable)
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have included all relevant version information
          required: true
        - label: I have provided steps to reproduce the issue
          required: true
        - label: I have included relevant logs or error messages
          required: false
